### ISSUE TITLE
Browserifying AngularJS Apps and Tests Tutorial

### ISSUE THREAD

**Issue by demisx** [bendrucker/ama#10]
Hi Ben, 
Any chance you could do a blog post on how to properly browserify an AngularJS app, including tests? With Angular 1.3.14 and 1.4 support for CommonJS modules and your top-notch Browserify/Angular expertise, I think this would be a very popular post. I've tried a couple tutorials about a month ago, but none of them were clear enough to get this in without a major hassle.  Guys around me had somewhat similar experience. 

Thank you.

**Comment by bendrucker** [comment]
Totally. Was actually thinking about doing that this weekend since literally every post out there is now totally out of date. You still need browserify-shim for certain things, but far fewer than before.

**Comment by demisx** [comment]
This is exactly the reason why myself and many around me haven't embraced the browserify on the angular side yet. A good tutorial would be to take a traditional basic app (e.g. angular-phonecat, to-do list etc.) and then port it to browserify step-by-step using the latest Angular 1.4, for example. I can help out with testing and feedback, if needed. I can also then present your approach (with credits to you) at our local Angular meetups.

Will be waiting patiently for this to come.

**Comment by bendrucker** [comment]
Yeah, I figure this is a full day effort to properly write and document. Got my first free weekend in weekends coming up and hoping to devote Saturday to it.

**Comment by bendrucker** [comment]
Never got around to this. Not really a priority for me these days. If I can answer specific structural questions by all means open a new issue.
