### ISSUE TITLE
Bookshelf vs. LoopBack persistence layer

### ISSUE THREAD

**Issue by nareshbhatia** [bendrucker/ama#13]
Hi Ben,

I have been evaluating the [LoopBack Framework](https://strongloop.com/node-js/loopback-framework/) to speed up API development for my applications. Overall, I like it a lot - I can start with defining my models and relations and expose them quickly via a REST API. The power is really in the REST API portion where I get the ability to specify what related entities I want to fetch, how I want to filter, paginate etc. - all out-of-the-box. However, I am not sure how good the persistence layer is compared to Bookshelf. By any chance have you done an evaluation? Do you have an opinion?

Do you think there is value in creating a REST library that translates complex REST requests into Bookshelf queries?

Thanks.
Naresh

**Comment by bendrucker** [comment]
To be honest I have zero knowledge of LoopBack. The tradeoff with managed services like that is always extensibility versus ease of use. If you exceed its bounds it can become a net negative, but if you play within its sandbox it could be great. 

Re: REST -> Bookshelf, see https://github.com/endpoints/endpoints

**Comment by nareshbhatia** [comment]
That's exactly what worries me in selecting a managed service.

Thanks for pointing me to endpoints. It looks very promising. Since my buddy Bob Holt is a committer, I have a feeling that it has a good future!
