### ISSUE TITLE
Promise patterns

### ISSUE THREAD

**Issue by bsiddiqui** [bendrucker/ama#16]
If you have a function you want to call on the result of a promise, is there any downside to adding it to the promise chain?

i.e. given some format function that doesn't return a promise

``` js
format = function (user) {
   return { ... }
}
```

is there any reason you should do 

``` js
return User.forge({ id: id }).fetch()
.then(function (user) {
   reply(format(user))
}, reply)
```

instead of 

``` js
return User.forge({ id: id }).fetch()
.then(format)
.then(reply, reply)
```

the former avoids adding another promise to the chain but the ladder looks cleaner

**Comment by bendrucker** [comment]
You should take advantage of Promises for readable flow control and go with the latter style. A good promise library (e.g. Bluebird) will realize that `format` isn't returning a thenable and introduce some performance optimizations.

**Comment by bsiddiqui** [comment]
👍
