### ISSUE TITLE
Using promise.finally

### ISSUE THREAD

**Issue by bsiddiqui** [bendrucker/ama#17]
I've been trying to get a better understanding of when to use Bluebird's [.finally](https://github.com/petkaantonov/bluebird/blob/master/API.md#finallyfunction-handler---promise). Since it's called regardless of the promise's fate, it sounds like

``` js
return somePromise()
.finally(doSomething)
```

is doing something similar to 

``` js
return somePromise()
.then(doSomething, doSomething)
```

I've had a couple situations where they haven't reacted in the same way so when would you use [.finally](https://github.com/petkaantonov/bluebird/blob/master/API.md#finallyfunction-handler---promise)?

**Comment by bendrucker** [comment]
1 is definitely not equivalent to 2. Finally is there for when you want to do something regardless of outcome. There is no input to `doSomething` whereas in case 2 you're shoving two random inputs in there which won't go well.

``` js
function load () {
  loading.set(true)
  return getData()
    .then(data.set)
    .catch(error.set)
    .finally(function () {
      loading.set(false)
    })
}
```

`loading.set(false)` should always be evaluated when we're all done, regardless of the outcome. And its evaluation should happen after a promise resolves, but doesn't depend on the fulfillment value of `getData`
