### ISSUE TITLE
What tool(s) do you use for logging front-end errors?

### ISSUE THREAD

**Issue by chinedufn** [bendrucker/ama#18]
Ey,

How would you recommend going about logging errors on the front-end?

Cheers and thanks

**Comment by bendrucker** [comment]
[Sentry](https://getsentry.com/welcome/) for the majority of exceptions. Once you start figuring out which exceptions are expected and not dev error, e.g. a user denying geolocation, you can start tracking those to a separate analytics pipeline as normal application events.
