### ISSUE TITLE
Bookshelf relation() vs. related('relation')

### ISSUE THREAD

**Issue by bsiddiqui** [bendrucker/ama#3]
In describing [attach](http://bookshelfjs.org/#Model-attach), the Bookshelf docs show two ways to use the method.

``` js
// approach 1
new Site({id: 1}).related('admins').attach([1, 2]);

// approach 2
new Site({id: 1}).admins().attach([1, 2]);
```

Is there a difference in these two approach? Also, is `attach` supposed to respond with any data?

I looked through the [source code](https://github.com/tgriesser/bookshelf/blob/420ce97ee1cdb97b2d1e77173b06f3c163894cec/lib/relation.js#L374-382) and it seems like there is an "attached" event but I haven't seen what kind of response it should be giving - I've been getting an empty array.

**Comment by bendrucker** [comment]
No real difference. The difference between `.related('admins') and`.admins()`is that the former calls`site.admins()`and stores the return value as`site.relations.admins`. The later just returns a new collection with the right`relatedData` bound. 

What do you mean by response for the event?

**Comment by bsiddiqui** [comment]
Sorry I mean what kind of response should `.attach()` return? 

If I do:

``` js
return new Site({id: 1}).admins().attach([1, 2])
.then(function (res) {
   console.log(res); // empty array
});
```

Maybe I have my models setup incorrectly.

**Comment by bendrucker** [comment]
Yeah that's the resolution value of `triggerThen` I believe. It's really not resolving anything intentionally at the moment. What would you expect/want it to resolve?

**Comment by bsiddiqui** [comment]
I would expect that it would resolve with the model that was created or the collection it was added to

**Comment by bsiddiqui** [comment]
With the way it currently resolves, how would you recommend check if you successfully created the model and respond with it?

**Comment by bendrucker** [comment]
What exactly are you looking to get in the end? The `Site`? The admins with IDs 1 and 2?

**Comment by bsiddiqui** [comment]
I guess I'd be interested in both since this is hypothetical - how would you do it in either situation?

**Comment by bendrucker** [comment]
Well I'm asking because it would be sloppy right now with the need to store both the `site` and `adminIds` in a variable so you can use them later. I think it makes sense to resolve the collection and I can go commit that if it makes sense.

**Comment by bsiddiqui** [comment]
Yeah that makes sense :+1:
