### ISSUE TITLE
Search in postgres

### ISSUE THREAD

**Issue by bsiddiqui** [bendrucker/ama#4]
Hey Ben - how do you typically handle search or, more specifically, fuzzy search when using Postgres? At what point do you decide that doing SQL queries through knex isn't enough and you want to shift to something more robust like elastic search?

**Comment by bendrucker** [comment]
This isn't something I'm an expert in. As a general rule, Postgres full text search is usually good enough. It's not going to perform as well as Elastic and it's not going to have as many features. But it's also one fewer service and and API to maintain. The plan with Knex is to switch to a browserify-esque pipeline of transformers. I'll be taking over the majority of the front end features like migrations and schema. Better support for all the various Postgres features should be less of an undertaking.

**Comment by bsiddiqui** [comment]
:+1:

**Comment by demisx** [comment]
:+1:
